name: Qodana

on: [ push, pull_request, workflow_dispatch ]

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:

        - name: Checkout
          uses: actions/checkout@v3

        - name: 'Qodana Scan'
          uses: JetBrains/qodana-action@v2022.3.4
          with:
            linter: jetbrains/qodana-jvm

        - uses: github/codeql-action/upload-sarif@v1
          with:
            sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
